export const DUMMY_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

export const DEMO_FOLDERS = [
  "Personal",
  "Work",
  "Finance",
  "Health",
  "Travel",
  "Vehicle",
  "Legal",
  "Property",
  "Utilities",
  "Education",
  "Insurance",
  "Other",
];

export interface MockTemplate {
  name: string;
  category: string;
  fileType: string;
  expiryOffsetDays?: number;
  baseExpiryDays?: number;
  isFavorite: boolean;
  isDeleted: boolean;
  deletedOffsetDays?: number;
  hasFile?: boolean;
}

export const MOCK_TEMPLATES: MockTemplate[] = [
  // --- Personal ---
  {
    name: "Passport 2026.pdf",
    category: "Personal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 3,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Driver License.jpg",
    category: "Personal",
    fileType: "image",
    expiryOffsetDays: 365 * 5,
    isFavorite: true,
    isDeleted: false,
    hasFile: true,
  },
  {
    name: "Aadhaar Card.png",
    category: "Personal",
    fileType: "image",
    expiryOffsetDays: 365 * 10,
    isFavorite: false,
    isDeleted: false,
    hasFile: true,
  },
  {
    name: "Voter ID Card.pdf",
    category: "Personal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 10,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "PAN Card.png",
    category: "Personal",
    fileType: "image",
    expiryOffsetDays: 365 * 15,
    isFavorite: false,
    isDeleted: false,
    hasFile: true,
  },
  {
    name: "Birth Certificate.pdf",
    category: "Personal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 50,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Marriage Certificate.pdf",
    category: "Personal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 50,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Passport Photo.jpg",
    category: "Personal",
    fileType: "image",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
    hasFile: true,
  },
  {
    name: "Old Gym Card.png",
    category: "Personal",
    fileType: "image",
    expiryOffsetDays: -20,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 5,
    hasFile: true,
  },
  {
    name: "Expired Bus Pass.pdf",
    category: "Personal",
    fileType: "pdf",
    expiryOffsetDays: -45,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 12,
  },

  // --- Work ---
  {
    name: "Employment Offer Letter.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 30,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Work Agreement.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "NDA Contract.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 365 * 2,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Salary Slip Jan.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 60,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Salary Slip Feb.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 90,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Salary Slip Mar.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 120,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Salary Slip Apr.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 150,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Salary Slip May.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 180,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Experience Certificate.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 365 * 5,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Relieving Letter.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: 365 * 5,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Deprecated NDA.pdf",
    category: "Work",
    fileType: "pdf",
    expiryOffsetDays: -120,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 8,
  },

  // --- Finance ---
  {
    name: "Tax Return 2024.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 150,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Tax Return 2023.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: -200,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Tax Return 2022.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: -560,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Bank Statement Q1.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 45,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Bank Statement Q2.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 135,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Credit Card Statement.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 20,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Mortgage Statement.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Mutual Fund Portfolio.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 180,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Stock Portfolio 2025.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 240,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Dividend Income Report.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: 90,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Old Invoice 2021.pdf",
    category: "Finance",
    fileType: "pdf",
    expiryOffsetDays: -1000,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 20,
  },

  // --- Health ---
  {
    name: "Medical Checkup Report.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 180,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Blood Test Summary.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 90,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Vaccination Record.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 365 * 3,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Dental Prescription.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 120,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Eye Test Prescription.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Pet Vaccination Card.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 300,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Fitness Progress Log.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: 15,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Obsolete Prescription.pdf",
    category: "Health",
    fileType: "pdf",
    expiryOffsetDays: -60,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 18,
  },

  // --- Travel ---
  {
    name: "Schengen Visa.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: 90,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "US Tourist Visa.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: 365 * 8,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Flight Ticket - London.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: 5,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Hotel Booking Voucher.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: 8,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Travel Insurance Plan.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: 12,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Pet Passport.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: 365 * 2,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Expired Visa 2019.pdf",
    category: "Travel",
    fileType: "pdf",
    expiryOffsetDays: -1500,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 1,
  },

  // --- Vehicle ---
  {
    name: "Car Registration Card.pdf",
    category: "Vehicle",
    fileType: "pdf",
    expiryOffsetDays: 365 * 5,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "PUC Pollution Certificate.pdf",
    category: "Vehicle",
    fileType: "pdf",
    expiryOffsetDays: 15,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Driving School Certificate.pdf",
    category: "Vehicle",
    fileType: "pdf",
    expiryOffsetDays: 365 * 10,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Car Maintenance Bill.pdf",
    category: "Vehicle",
    fileType: "pdf",
    expiryOffsetDays: -10,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Vehicle Fitness Certificate.pdf",
    category: "Vehicle",
    fileType: "pdf",
    expiryOffsetDays: 120,
    isFavorite: false,
    isDeleted: false,
  },

  // --- Legal ---
  {
    name: "Power of Attorney.pdf",
    category: "Legal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 3,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Will & Testament.pdf",
    category: "Legal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 15,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Trust Deed.pdf",
    category: "Legal",
    fileType: "pdf",
    expiryOffsetDays: 365 * 20,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Partnership Agreement.pdf",
    category: "Legal",
    fileType: "pdf",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Legal Notice.pdf",
    category: "Legal",
    fileType: "pdf",
    expiryOffsetDays: -25,
    isFavorite: false,
    isDeleted: false,
  },

  // --- Property ---
  {
    name: "House Lease Deed.pdf",
    category: "Property",
    fileType: "pdf",
    expiryOffsetDays: 240,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Rent Agreement.pdf",
    category: "Property",
    fileType: "pdf",
    expiryOffsetDays: 180,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Property Tax Receipt.pdf",
    category: "Property",
    fileType: "pdf",
    expiryOffsetDays: 300,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Home Loan Statement.pdf",
    category: "Property",
    fileType: "pdf",
    expiryOffsetDays: 60,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Sale Deed Copy.pdf",
    category: "Property",
    fileType: "pdf",
    expiryOffsetDays: 365 * 10,
    isFavorite: false,
    isDeleted: false,
  },

  // --- Utilities ---
  {
    name: "Electricity Bill Jan.pdf",
    category: "Utilities",
    fileType: "pdf",
    expiryOffsetDays: 12,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Water Connection Bill.pdf",
    category: "Utilities",
    fileType: "pdf",
    expiryOffsetDays: 25,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Internet Subscription.pdf",
    category: "Utilities",
    fileType: "pdf",
    expiryOffsetDays: 150,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Gas Pipeline Agreement.pdf",
    category: "Utilities",
    fileType: "pdf",
    baseExpiryDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Broadband Bill.pdf",
    category: "Utilities",
    fileType: "pdf",
    expiryOffsetDays: 22,
    isFavorite: false,
    isDeleted: false,
  },

  // --- Education ---
  {
    name: "Degree Transcript.pdf",
    category: "Education",
    fileType: "pdf",
    expiryOffsetDays: 365 * 10,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Diploma Certificate.pdf",
    category: "Education",
    fileType: "pdf",
    expiryOffsetDays: 365 * 10,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "React Course Certificate.pdf",
    category: "Education",
    fileType: "pdf",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "College ID Card.png",
    category: "Education",
    fileType: "image",
    expiryOffsetDays: 180,
    isFavorite: false,
    isDeleted: false,
    hasFile: true,
  },
  {
    name: "Recommendation Letter.pdf",
    category: "Education",
    fileType: "pdf",
    expiryOffsetDays: 365 * 2,
    isFavorite: false,
    isDeleted: false,
  },

  // --- Insurance ---
  {
    name: "Health Insurance Policy.pdf",
    category: "Insurance",
    fileType: "pdf",
    expiryOffsetDays: 250,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Life Insurance Policy.pdf",
    category: "Insurance",
    fileType: "pdf",
    expiryOffsetDays: 365 * 4,
    isFavorite: true,
    isDeleted: false,
  },
  {
    name: "Term Insurance Policy.pdf",
    category: "Insurance",
    fileType: "pdf",
    expiryOffsetDays: 365 * 10,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Vehicle Insurance Certificate.pdf",
    category: "Insurance",
    fileType: "pdf",
    expiryOffsetDays: 180,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Home Insurance Policy.pdf",
    category: "Insurance",
    fileType: "pdf",
    expiryOffsetDays: 300,
    isFavorite: false,
    isDeleted: false,
  },

  // --- Other ---
  {
    name: "Gym Membership Card.png",
    category: "Other",
    fileType: "image",
    expiryOffsetDays: 30,
    isFavorite: false,
    isDeleted: false,
    hasFile: true,
  },
  {
    name: "Library Membership.pdf",
    category: "Other",
    fileType: "pdf",
    expiryOffsetDays: 120,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Phone Warranty PDF.pdf",
    category: "Other",
    fileType: "pdf",
    expiryOffsetDays: 300,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Laptop Invoice.pdf",
    category: "Other",
    fileType: "pdf",
    expiryOffsetDays: 365,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "AC Maintenance Receipt.pdf",
    category: "Other",
    fileType: "pdf",
    expiryOffsetDays: -5,
    isFavorite: false,
    isDeleted: false,
  },
  {
    name: "Broken Charger Warranty.pdf",
    category: "Other",
    fileType: "pdf",
    expiryOffsetDays: -30,
    isFavorite: false,
    isDeleted: true,
    deletedOffsetDays: 25,
  },
];
